/// <reference types="cypress" />

import ConstantsObjects from '../../utils/constants/consts'

const consts = new ConstantsObjects()

context('cenarios de testes para o site Burger Eats', () => {

    beforeEach(() => {
        cy.visit('https://buger-eats.vercel.app/')
    })

    it('validar existencia do button para cadastro de entregador', () => {
        cy.get('a').should('exist')
    });

    it('validar cadastro de entregador que utiliza moto', () => {
        cy.get('a').click()
        cy.get(consts.input_name)
            .should('exist')
            .clear()
            .type('Abner Gonçalves')
        cy.get(consts.input_cpf)
            .should('exist')
            .clear()
            .type('37685739070')
        cy.get(consts.input_email)
            .should('exist')
            .clear()
            .type('teste@teste.com')
        cy.get(consts.input_whats)
            .should('exist')
            .clear()
            .type('11999999999')
        cy.get(consts.input_cep)
            .should('exist')
            .clear()
            .type('09170120')
        cy.get(':nth-child(3) > :nth-child(2) > :nth-child(2) > input').click()
        cy.get(consts.input_num_resid)
            .should('exist')
            .clear()
            .type('55')
        cy.get(consts.option_moto).click()
        const ft = 'ftdeperfil.jpg'
        cy.get("input[type='file']")
            //.click()
            .attachFile(ft)
        cy.get('.button-success').click()
        cy.wait(100)
        cy.get('div[class="swal2-popup swal2-modal swal2-icon-success swal2-show"]').should('exist')
    })

    it('validar cadastro de entregador que utiliza bicicleta', () => {
        cy.get('a').click()
        cy.get(consts.input_name)
            .should('exist')
            .clear()
            .type('Abner Gonçalves')
        cy.get(consts.input_cpf)
            .should('exist')
            .clear()
            .type('37685739070')
        cy.get(consts.input_email)
            .should('exist')
            .clear()
            .type('teste@teste.com')
        cy.get(consts.input_whats)
            .should('exist')
            .clear()
            .type('11999999999')
        cy.get(consts.input_cep)
            .should('exist')
            .clear()
            .type('09170120')
        cy.get(':nth-child(3) > :nth-child(2) > :nth-child(2) > input').click()
        cy.get(consts.input_num_resid)
            .should('exist')
            .clear()
            .type('55')
        cy.get(consts.option_bicicleta).click()
        const ft = 'ftdeperfil.jpg'
        cy.get("input[type='file']")
            //.click()
            .attachFile(ft)
        cy.get('.button-success').click()
        cy.wait(100)
        cy.get('div[class="swal2-popup swal2-modal swal2-icon-success swal2-show"]').should('exist')
    })

    it('validar cadastro de entregador que utiliza van', () => {
        cy.get('a').click()
        cy.get(consts.input_name)
            .should('exist')
            .clear()
            .type('Abner Gonçalves')
        cy.get(consts.input_cpf)
            .should('exist')
            .clear()
            .type('37685739070')
        cy.get(consts.input_email)
            .should('exist')
            .clear()
            .type('teste@teste.com')
        cy.get(consts.input_whats)
            .should('exist')
            .clear()
            .type('11999999999')
        cy.get(consts.input_cep)
            .should('exist')
            .clear()
            .type('09170120')
        cy.get(':nth-child(3) > :nth-child(2) > :nth-child(2) > input').click()
        cy.get(consts.input_num_resid)
            .should('exist')
            .clear()
            .type('55')
        cy.get(consts.option_van).click()
        const ft = 'ftdeperfil.jpg'
        cy.get("input[type='file']")
            //.click()
            .attachFile(ft)
        cy.get('.button-success').click()
        cy.wait(100)
        cy.get('div[class="swal2-popup swal2-modal swal2-icon-success swal2-show"]').should('exist')
    })
    context('cenarios para validar obrigatoriedade de informações no cadastros', () => {
        it('validar obrigatoriedade do name para o cadastro de um entregador', () => {
            cy.get('a').click()
            cy.get(consts.input_cpf)
                .should('exist')
                .clear()
                .type('37685739070')
            cy.get(consts.input_email)
                .should('exist')
                .clear()
                .type('teste@teste.com')
            cy.get(consts.input_whats)
                .should('exist')
                .clear()
                .type('11999999999')
            cy.get(consts.input_cep)
                .should('exist')
                .clear()
                .type('09170120')
            cy.get(':nth-child(3) > :nth-child(2) > :nth-child(2) > input').click()
            cy.get(consts.input_num_resid)
                .should('exist')
                .clear()
                .type('55')
            cy.get(consts.option_van).click()
            const ft = 'ftdeperfil.jpg'
            cy.get("input[type='file']")
                //.click()
                .attachFile(ft)
            cy.get('.button-success').click()
            cy.wait(100)
            cy.get('span[class="alert-error"]').should('exist')
        })

        it('validar obrigatoriedade do cpf para o cadastro de um entregador', () => {
            cy.get('a').click()
            cy.get(consts.input_name)
                .should('exist')
                .clear()
                .type('Abner Gonçalves')
            cy.get(consts.input_email)
                .should('exist')
                .clear()
                .type('teste@teste.com')
            cy.get(consts.input_whats)
                .should('exist')
                .clear()
                .type('11999999999')
            cy.get(consts.input_cep)
                .should('exist')
                .clear()
                .type('09170120')
            cy.get(':nth-child(3) > :nth-child(2) > :nth-child(2) > input').click()
            cy.get(consts.input_num_resid)
                .should('exist')
                .clear()
                .type('55')
            cy.get(consts.option_van).click()
            const ft = 'ftdeperfil.jpg'
            cy.get("input[type='file']")
                //.click()
                .attachFile(ft)
            cy.get('.button-success').click()
            cy.wait(100)
            cy.get('span[class="alert-error"]').should('exist')
        })





    })
})